DROP DATABASE IF EXISTS `ResearchPaper`;
CREATE DATABASE `ResearchPaper`;
USE `ResearchPaper`;

CREATE TABLE Paper (
    PaperID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255),
    Path VARCHAR(255)
);

CREATE TABLE FigureSummary (
    FigureID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PaperID INT NOT NULL,
    Summary TEXT,
    FOREIGN KEY(PaperID) REFERENCES Paper(PaperID)
);

CREATE TABLE TableSummary (
    TableID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PaperID INT NOT NULL,
    Summary TEXT,
    FOREIGN KEY(PaperID) REFERENCES Paper(PaperID)
);

CREATE TABLE TextSummary (
    TextID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PaperID INT NOT NULL,
    Summary TEXT,
    FOREIGN KEY(PaperID) REFERENCES Paper(PaperID)
);

CREATE TABLE Results (
    ResultsID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PaperID INT NOT NULL,
    Path VARCHAR(255),
    FOREIGN KEY(PaperID) REFERENCES Paper(PaperID)
);
